name: "Build"

on:
  workflow_dispatch:
  push:

permissions:
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    name: Build
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@main
    - uses: NixOS/nix-installer-action@main
    - uses: Mic92/niks3-action@main
      with:
        server-url: https://niks3.usertam.dev
    - name: Build
      run: |
        nix build --print-build-logs
        if ! nix build --rebuild --keep-failed 2>stderr; then
          echo "::warning::$(grep 'error: ' stderr)"
          diff -ar $(nix eval --raw){,.check} || true
        fi
